1-ShopApp/ViewModels/ProductViewModel.cs
using Azure;
using shopapp.entity;

namespace _1_ShopApp.ViewModels 
{
public class PageInfo
{
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }   
        public int CurrentPage { get; set; }
        public string CurrentCategory { get; set; }

        public int TotalPages()
        {
                return (int)Math.Ceiling((decimal)TotalItems/ItemsPerPage);
        }
}


public class ProductListModel
{
        public PageInfo PageInfo { get; set; }
        public List<Product> Products { get; set; }
}

}

1-ShopApp/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _1_ShopApp.Identity;
using _1_ShopApp.Models;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using shopapp.business.Abstract;
using shopapp.entity;

namespace _1_ShopApp.Controllers
{
    [Authorize]
    public class CartController: Controller
    {
        private ICartService _cartService;
        private UserManager<User> _userManager;
        private IOrderService _orderService;
        public CartController(ICartService cartService, UserManager<User> userManager, IOrderService orderService)
        {
            _cartService = cartService;
            _userManager = userManager;
            _orderService = orderService; 
        }

        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            return View(new CartModel() {

                CartId = cart.Id,
                CartItems = cart.CardItems.Select(i=> new CartItemModel ()
                {
                        CartItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            var userId = _userManager.GetUserId(User);

            _cartService.AddtoCart(userId,productId,quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.DeleteFromCart(userId,productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            var ordermodel = new OrderModel();
            ordermodel.CartModel = new CartModel(){
                CartId = cart.Id,
                CartItems = cart.CardItems.Select(i=> new CartItemModel ()
                {
                        CartItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                }).ToList()
            };
            
            return View(ordermodel);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderModel model)
        {
            if(!ModelState.IsValid)
            {

            var userId = _userManager.GetUserId(User);
            var cart = _cartService.GetCartByUserId(userId);

            model.CartModel = new CartModel(){
                CartId = cart.Id,
                CartItems = cart.CardItems.Select(i=> new CartItemModel ()
                {
                        CartItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                }).ToList()
            };

                var payment = await PaymentProcess(model);

                if(payment.Status == "success")
                {
                        SaveOrder(model,payment,userId);
                        ClearCart(model.CartModel.CartId);
                        return View("Success");
                }
                else
                {
                    var msg = new AlertMessage()
                    {
                        Message = $"{payment.ErrorMessage}",
                        AlertType = "danger"
                    };
                    TempData["message"] = JsonConvert.SerializeObject(msg);
                }
            }
            return View(model);
        }

        public IActionResult GetOrders()
        {
            var userId = _userManager.GetUserId(User);
           var orders = _orderService.GetOrders(userId);

            var orderlistModel = new List<OrderListModel>();
            OrderListModel orderModel; 

            foreach(var item in orders)
            {
                orderModel = new OrderListModel();

                orderModel.OrderId = item.Id;
                orderModel.OrderNumber = item.OrderNumber;
                orderModel.OrderDate = item.OrderDate;
                orderModel.Phone = item.Phone;
                orderModel.FirstName = item.FirstName;
                orderModel.LastName = item.LastName;
                orderModel.Email = item.Email;
                orderModel.Adress = item.Adress;
                orderModel.City = item.City;
                orderModel.OrderState = item.OrderState;
                orderModel.PaymentType = item.PaymentType;

                orderModel.OrderItems = item.OrderItems.Select(i=> new OrderItemModel() {

                    OrderItemId = i.Id,
                    Name = i.Product.Name,
                    Price = (double)i.Price,
                    Quantity = i.Quantity,
                    ImageUrl = i.Product.ImageUrl


                }).ToList();

                orderlistModel.Add(orderModel);
            }

            return View("Orders", orderlistModel);
        }

        private void ClearCart(int CartId)
        {
            _cartService.ClearCart(CartId);
        }

        private void SaveOrder(OrderModel model, Payment payment, string? userId)
        {
            var order = new Order();
            order.OrderNumber = new Random().Next(111111,999999).ToString();
            order.OrderState = EnumOrderState.completed;
            order.PaymentType = EnumPaymentType.CreditCard;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.UserId = userId;
            order.Adress = model.Address;
            order.Phone = model.Phone;
            order.Email = model.Email;
            order.City = model.City;
            order.Note = model.Note;
            order.OrderItems = new List<shopapp.entity.OrderItem>();

            foreach(var item in model.CartModel.CartItems)
            {
                var orderItem = new shopapp.entity.OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId
                };
                order.OrderItems = new List<shopapp.entity.OrderItem>();
                order.OrderItems.Add(orderItem);
            }
            _orderService.Create(order);

        }

       private async Task<Payment> PaymentProcess(OrderModel model)
        {
              Options options = new Options();
                options.ApiKey = "sandbox-byv7vQA4R5fvRgvWCRVP4nETXQyGydM8";
                options.SecretKey = "sandbox-5UNdIVrzY8dainYgSCESYATRBPQUqDtO";
                options.BaseUrl = "https://sandbox-api.iyzipay.com";
                        
                CreatePaymentRequest request = new CreatePaymentRequest();
                request.Locale = Locale.TR.ToString();
                request.ConversationId = new Random().Next(111111111,999999999).ToString();
                request.Price = model.CartModel.TotalPrice().ToString();
                request.PaidPrice = model.CartModel.TotalPrice().ToString();
                request.Currency = Currency.TRY.ToString();
                request.Installment = 1;
                request.BasketId = "B67832";
                request.PaymentChannel = PaymentChannel.WEB.ToString();
                request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

                PaymentCard paymentCard = new PaymentCard();
                paymentCard.CardHolderName = model.CardName;
                paymentCard.CardNumber = model.CardNumber;
                paymentCard.ExpireMonth = model.ExpirationMonth;
                paymentCard.ExpireYear = model.ExpirationYear;
                paymentCard.Cvc = model.Cvc;
                paymentCard.RegisterCard = 0;
                request.PaymentCard = paymentCard;

                // paymentCard.CardNumber = "5528790000000008";
                // paymentCard.ExpireMonth = "12";
                // paymentCard.ExpireYear = "2030"; 
                // paymentCard.Cvc = "123";

                Buyer buyer = new Buyer();
                buyer.Id = "BY789";
                buyer.Name = model.FirstName;
                buyer.Surname = model.LastName;
                buyer.GsmNumber = model.Phone;
                buyer.Email = model.Email;
                buyer.IdentityNumber = "74300864791";
                buyer.LastLoginDate = "2015-10-05 12:43:35";
                buyer.RegistrationDate = "2013-04-21 15:12:09";
                buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
                buyer.Ip = "85.34.78.112";
                buyer.City = model.City;
                buyer.Country = "Turkey";
                buyer.ZipCode = "34732";
                request.Buyer = buyer;

                Address shippingAddress = new Address();
                shippingAddress.ContactName = "Jane Doe";
                shippingAddress.City = "Istanbul";
                shippingAddress.Country = "Turkey";

1-ShopApp/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _1_ShopApp.Models;
using _1_ShopApp.ViewModels;
using Azure;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.entity;

namespace _1_ShopApp.Controllers
{
    public class ShopController:Controller
    {
        private IProductService _productService;
        public ShopController(IProductService productService)
        {
            this._productService = productService;
        }


        // localhost/products/telefon?page=1
        public IActionResult List(string category, int page=1) // varsayılan olarak 1 olsun page
        {
            const int pageSize= 2;
            var productViewModel = new ProductListModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category), 
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Products = _productService.GetProductsByCategory(category, page, pageSize)
            };
            return View(productViewModel);
        }

        public IActionResult Details(string url)
        {
            if(url==null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails(url);
            if(product == null)
            {
                return NotFound();
            }
            return View(new ProductDetailModel{
                Products = product,
                Categories = product.ProductCategories.Select(i=>i.Category).ToList()
            });
        }

        public IActionResult Search(string q)
        {
            var productViewModel = new ProductListModel()
            {
               Products = _productService.GetSearchResult(q)
            };
            return View(productViewModel);
        }

    }
}

1-ShopApp/Views/Shared/_categories.cshtml
@model List<shopapp.entity.Category>

<div class="list-group">
        @foreach (var item in Model)
        {
            <a href="#" class="list-group-item list-group-item-action">@item.Name</a>
        }
    </div>
    

1-ShopApp/Views/Shared/_header.cshtml
<header>
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">Shop App</h1>
                <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum possimus corporis mollitia, eligendi cupiditate doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, architecto!</p>
            </div>
        </div>
    </header>

1-ShopApp/Views/Shared/_layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    @RenderSection("Css",false)
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
</head>
<body>

    @await Html.PartialAsync("_navbar")
        
     <main class="my-3">
        <div class="container">

            @if (TempData["message"] != null)
            {
                <partial name="_resultMessage" model="@(TempData.Get<AlertMessage>("message"))"> </partial>

            }

        @RenderBody() 
        </div>
    </main>     

    <footer class="py-5 bg-dark text-white text-center">
        Shop App | 30.10.2024
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.2/css/all.css">
    @RenderSection("Scripts",false)

</body>
</html>

1-ShopApp/Views/Shared/_navbar.cshtml
@using Microsoft.AspNetCore.Identity

<div class="navbar bg-danger navbar-dark navbar-expand-sm">
    <div class="container">
        <a href="/" class="navbar-brand">ShopApp</a>
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a href="/products" class="nav-link">Products</a>
            </li>

                
            @if(User.Identity.IsAuthenticated)
            {
                <li class="nav-item">
                    <a href="/cart" class="nav-link">Cart</a>
                </li>
                <li class="nav-item">
                    <a href="/orders" class="nav-link">Orders</a>
                </li>

                if(User.IsInRole("admin"))
                {
                @* <li class="nav-item">
                    <a asp-controller="admin" asp-action="createproduct" class="nav-link">Add Product</a>
                </li> *@
                <li class="nav-item">
                    <a href="/admin/products" class="nav-link">Admin Products</a>
                </li>
                <li class="nav-item">
                    <a href="/admin/categories" class="nav-link">Admin Categories</a>
                </li>
                <li class="nav-item">
                    <a href="/admin/role/list" class="nav-link">Roles</a>
                </li>
                <li class="nav-item">
                    <a href="/admin/user/list" class="nav-link">Users</a>
                </li>
                }

            }
        </ul>
        

        <ul class="navbar-nav ml-auto">

            @if(User.Identity.IsAuthenticated)
            {
                <li class="nav-item">
                    <a href="/account/manage" class="nav-link">
                        @User.Identity.Name
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/account/logout" class="nav-link">Logout</a>
                </li>
            }
            else 
            {
                <li class="nav-item">
                    <a href="/account/login" class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                    <a href="/account/register" class="nav-link">Register</a>
                </li>
            }
        </ul>

    </div>
</div>

1-ShopApp/Views/Shared/_noproduct.cshtml
<div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-danger">
                            Ürün yok.
                        </div>
                    </div>
</div>

1-ShopApp/Views/Shared/_product.cshtml
@model Product

<div class="card mb-2">
    <img class="card-img-top" src="~/images/@Model.ImageUrl" alt="Product Image">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <small class="text-muted">
            <i class="fas fa-lira-sign"></i>@Model.Price
        </small> 
    </div>
    <div class="card-footer text-center">
        <a asp-controller="Shop" asp-action="Details" asp-route-url="@Model.Url" class="btn btn-primary btn-sm">İncele</a>

        @if(User.Identity.IsAuthenticated)
        {
            <form asp-controller="Cart" asp-action="AddToCart" method="POST" style="display: inline;">
                <input type="hidden" name="productId" value="@Model.ProductId">
                <input type="hidden" name="quantity" value="1">
                <button type="submit" class="btn btn-primary btn-sm">Add To Cart</button>
            </form>
        }
    </div>
</div>

1-ShopApp/Views/Shared/_resultMessage.cshtml
@model AlertMessage

<div class="row">
    <div class="col-md-12">
            <div class="alert alert-@Model.AlertType">
                <h4 class="alert-title">@Model.Title</h4>
                <p>@Model.Message</p>
            </div>
    </div>
</div>
 

1-ShopApp/Views/Shared/_search.cshtml
<div class="card mt-3">
    <div class="card-header">
        <h5>Search</h5>
    </div>
    <div class="card-body">
        <form action="/search">
            <div class="form-group row">
                <div class="col">
                    <input name="q" type="text" class="form-control" placeholder="Search">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-danger w-100">Ara</button>
                </div>
            </div>
        </form>
    </div>
</div>